In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Working with Dates

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [8]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
92  2019-05-30        5788        7      34       2019
14  2019-05-29        3833       26     240       2019
952 2018-08-18        6492       16       1       2018
165 2018-12-05         327       17       2       2018
149 2019-02-09        1024       10       2       2019

## 2. Extract Month

In [9]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [10]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

## Extract Days

In [11]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [12]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [13]:

# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [14]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

## Extract week of the year

In [15]:
date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [16]:
# Use isocalendar().week instead of .week which is deprecated
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,10,1,Tuesday,0,50
1,2018-08-15,2018,8,15,2,Wednesday,0,33
2,2018-10-23,2018,10,23,1,Tuesday,0,43
3,2019-08-17,2019,8,17,5,Saturday,1,33
4,2019-01-06,2019,1,6,6,Sunday,1,1

## Extract Quarter

In [17]:

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

## Extract Semester

In [18]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [19]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 2, 10, 9, 38, 4, 449137)

In [20]:
today - date['date']

0     2254 days 09:38:04.449137
1     2736 days 09:38:04.449137
2     2667 days 09:38:04.449137
3     2369 days 09:38:04.449137
4     2592 days 09:38:04.449137
                 ...
995   2682 days 09:38:04.449137
996   2623 days 09:38:04.449137
997   2471 days 09:38:04.449137
998   2536 days 09:38:04.449137
999   2310 days 09:38:04.449137
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
(today - date['date']).dt.days

0      2254
1      2736
2      2667
3      2369
4      2592
       ...
995    2682
996    2623
997    2471
998    2536
999    2310
Name: date, Length: 1000, dtype: int64

In [23]:
# Months passed
# Using 'D' (days) instead of 'M' and converting to approximate months
# A month is approximated as 30.44 days (365.25/12)
np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44, 0)

# Alternative approach using pandas if available:
# import pandas as pd
# pd.to_datetime(today).to_period('M') - pd.to_datetime(date['date']).to_period('M')

0      74.0
1      90.0
2      88.0
3      78.0
4      85.0
       ...
995    88.0
996    86.0
997    81.0
998    83.0
999    76.0
Name: date, Length: 1000, dtype: float64

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [25]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [26]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract Time part

In [28]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time difference

In [29]:
today - time['date']

0     4440 days 08:48:04.449137
1     4304 days 09:58:04.449137
2     4790 days 09:17:04.449137
3     4092 days 09:07:04.449137
4     4489 days 10:27:04.449137
                 ...
995   5079 days 08:48:04.449137
996   4400 days 10:24:04.449137
997   4865 days 10:01:04.449137
998   4981 days 10:04:04.449137
999   4253 days 10:13:04.449137
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.836477e+08
1      3.719015e+08
2      4.138894e+08
3      3.535816e+08
4      3.878872e+08
           ...
995    4.388573e+08
996    3.801974e+08
997    4.203721e+08
998    4.303946e+08
999    3.674960e+08
Name: date, Length: 1000, dtype: float64

In [31]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.394128e+06
1      6.198358e+06
2      6.898157e+06
3      5.893027e+06
4      6.464787e+06
           ...
995    7.314288e+06
996    6.336624e+06
997    7.006201e+06
998    7.173244e+06
999    6.124933e+06
Name: date, Length: 1000, dtype: float64

In [32]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      106568.801236
1      103305.967903
2      114969.284569
3       98217.117903
4      107746.451236
           ...
995    121904.801236
996    105610.401236
997    116770.017903
998    119554.067903
999    102082.217903
Name: date, Length: 1000, dtype: float64